### ISSUE TITLE
Thank you for your great work! May I get the original paper?

### ISSUE THREAD

**Issue by lkhit** [mestoking/FunctionApproximationIRL#1]
Hi, mestoking! I am now working on a large-scale state space, and continuous action space project. I am focused on the IRL algorithm,  can this algorithm applied to large-scale state space and continuous action space, may you share the paper with me? Thank you!!!

**Comment by mestoking** [comment]
Hi,

You can find the related preprint papers on:
https://arxiv.org/abs/1707.09394.

Our current formulation involves computing a maximum in action space,
therefore, it maybe more efficient in large but discrete action spaces. In
my personal testing (not shown in the paper), an observed state action pair
in an action space with one million actions can be processed in seconds
with GTX 1080. More actions can be processed if more GPU memories are
available. Personally I think one million actions should be enough to mimic
"continuous" for most robotics applications.

Thanks,
Kun

**Comment by lkhit** [comment]
Thanks.
